// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS47mYlvoqe1UE7rZ64ohGZUmQamG1b0I',
    appId: '1:349693462181:web:01728a25d3090b0417ef4c',
    messagingSenderId: '349693462181',
    projectId: 'you-only-park-once-8d476',
    authDomain: 'you-only-park-once-8d476.firebaseapp.com',
    storageBucket: 'you-only-park-once-8d476.appspot.com',
    measurementId: 'G-B9WNRN5SM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3i9gO4NcSU3tNSxcfrmbK-SdfN9wzNyo',
    appId: '1:349693462181:android:bfed2ca1d2863e1b17ef4c',
    messagingSenderId: '349693462181',
    projectId: 'you-only-park-once-8d476',
    storageBucket: 'you-only-park-once-8d476.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG9sBP1BK3oFVOFZUWRTkUVDykC87hzio',
    appId: '1:349693462181:ios:a2bfa98be5bd800a17ef4c',
    messagingSenderId: '349693462181',
    projectId: 'you-only-park-once-8d476',
    storageBucket: 'you-only-park-once-8d476.appspot.com',
    iosBundleId: 'com.example.thesisApplicationV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG9sBP1BK3oFVOFZUWRTkUVDykC87hzio',
    appId: '1:349693462181:ios:26bdd9a129f3fe7b17ef4c',
    messagingSenderId: '349693462181',
    projectId: 'you-only-park-once-8d476',
    storageBucket: 'you-only-park-once-8d476.appspot.com',
    iosBundleId: 'com.example.thesisApplicationV1.RunnerTests',
  );
}
